#ifndef ATMESH_COMMON_H_
#define ATMESH_COMMON_H_

#define ATMESH_STRINGIFY(x) #x
#define ATMESH_TOSTRING(x) ATMESH_STRINGIFY(x)

#define ATMESH_VERSION_MAJOR 1
#define ATMESH_VERSION_MINOR 0
#define ATMESH_VERSION_PATCH 0

#define ATMESH_VERSION_STRING \
    ATMESH_TOSTRING(ATMESH_VERSION_MAJOR) "." \
    ATMESH_TOSTRING(ATMESH_VERSION_MINOR) "." \
    ATMESH_TOSTRING(ATMESH_VERSION_PATCH)

#define ATMESH_APP_NAME "AtMesh " ATMESH_VERSION_STRING

#endif // ATMESH_COMMON_H_
